[package]
version = "0.1.0"
name = "contract_elf"
edition = "2021"

[dependencies]
sdk = { workspace = true, features = ["sp1"] }
contract = { path = "../lib", package = "contract"}
sp1-zkvm = { version = "4.1.0" }
